# Noise configuration file with customized noise:

qdevice_cfg: &qdevice_cfg
  num_qubits: 10000
  dummy: null
  init_time : 0
  measure_time : 0
  single_qubit_gate_depolar_prob : 0.0
  two_qubit_gate_depolar_prob : 0.0
  T1 : 0
  T2 : 0

link_cfg: &link_cfg
    # total length [km] of heralded connection (i.e. sum of fibers on both sides on midpoint station).
    length: 1.0
    # probability that photons are lost when entering connection the connection on either side.
    p_loss_init: 0.5
    # attenuation coefficient [dB/km] of fiber on either side.
    p_loss_length: 0.2
    # speed of light [km/s] in fiber on either side.
    speed_of_light: 200_000
    # dark-count probability per detection
    dark_count_probability: 0
    # probability that the presence of a photon leads to a detection event
    detector_efficiency: 1.0
    # Hong-Ou-Mandel visibility of photons that are being interfered (measure of photon indistinguishability)
    visibility: 1.0
    # determines whether photon-number-resolving detectors are used for the Bell-state measurement
    num_resolving: False



stacks:
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg: 
      <<: *qdevice_cfg

  - name: Alice
    qdevice_typ: generic
    qdevice_cfg: 
      <<: *qdevice_cfg

      

links:
  - stack1: Alice
    stack2: Bob
    typ: heralded
    cfg:
      <<: *link_cfg