# Noise configuration file with customized noise:


qdevice_cfg: &qdevice_cfg
  num_qubits: 100

  # coherence times (same for each qubit)
  T1: 36_000_000_000_000
  T2: 10_000_000_000

  # gate execution times
  init_time: 10_000
  single_qubit_gate_time: 20_000
  two_qubit_gate_time: 100_000
  measure_time: 10_000

  # noise model
  single_qubit_gate_depolar_prob: 0.05
  two_qubit_gate_depolar_prob: 0.1

  # note that depolar probability is time independent while T1T2 noise is time dependent. 
  # Either depolar probability or time related decoherence is applied at the same time. When it comes to collision, depolar probability has the higher priority.

link_cfg: &link_cfg
    # total length [km] of heralded connection (i.e. sum of fibers on both sides on midpoint station).
    length: 1.0
    # probability that photons are lost when entering connection the connection on either side.
    p_loss_init: 0
    # attenuation coefficient [dB/km] of fiber on either side.
    p_loss_length: 0
    # speed of light [km/s] in fiber on either side.
    speed_of_light: 200_000
    # dark-count probability per detection
    dark_count_probability: 0
    # probability that the presence of a photon leads to a detection event
    detector_efficiency: 1.0
    # Hong-Ou-Mandel visibility of photons that are being interfered (measure of photon indistinguishability)
    visibility: 1.0
    # determines whether photon-number-resolving detectors are used for the Bell-state measurement
    num_resolving: False



stacks:
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

links:
  - stack1: Alice
    stack2: Bob
    typ: heralded
    cfg:
      <<: *link_cfg