# Noise configuration file with customized noise:


qdevice_cfg: &qdevice_cfg
  num_qubits: 100

  # coherence times (same for each qubit)
  T1: 36_000_000_000_000
  T2: 10_000_000_000

  # gate execution times
  init_time: 10_000
  single_qubit_gate_time: 20_000
  two_qubit_gate_time: 100_000
  measure_time: 10_000

  # noise model
  single_qubit_gate_depolar_prob: 0.05
  two_qubit_gate_depolar_prob: 0.1

  # note that depolar probability is time independent while T1T2 noise is time dependent. 
  # Either depolar probability or time related decoherence is applied at the same time. When it comes to collision, depolar probability has the higher priority.


stacks:
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

links:
  - stack1: Alice
    stack2: Bob
    typ: perfect