# Perfect 2 node network, no noise from either computation on the nodes or communication between nodes
# Configuration with perfect link, a generic qdevice, but some noise on the generic device
qdevice_cfg: &qdevice_cfg
  num_qubits: 20

  # coherence times (same for each qubit)
  T1: 36_000_000_000_000
  T2: 10_000_000_000

  # gate execution times
  init_time: 10_000
  single_qubit_gate_time: 20_000
  two_qubit_gate_time: 100_000
  measure_time: 10_000

  # noise model
  single_qubit_gate_depolar_prob: 0.05
  two_qubit_gate_depolar_prob: 0.1

stacks:
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

links:
  - stack1: Alice
    stack2: Bob
    typ: perfect
    #cfg:
     # dummy: null